# Variables
@baseUrl = http://localhost:3333

### Listar todos os cursos
GET {{baseUrl}}/courses


### Listar um curso específico
GET {{baseUrl}}/courses/54ea161a-7b64-4d5f-93a1-d449c0c0ae21


### Criar um novo curso
POST {{baseUrl}}/courses
Content-Type: application/json

{
  "title": "Curso de Banco de dados",
  "description": "Curso sobre bancos de dados relacionais"
}
